### ISSUE TITLE
IdsDataGrid: Button events inside ids-data-grids are not triggering

### ISSUE THREAD

**Issue by suryapasem** [infor-design/enterprise-wc#1265]
I have a requirement where I should add 3 different buttons on one cell and I followed custom formatter syntax as below

<img width="672" alt="image" src="https://user-images.githubusercontent.com/132431453/235844577-2a1f7d80-f105-42d8-bfe3-86e0178e5f7d.png">

and the output is shown as expected 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/132431453/235844992-ef317e2d-793b-4cfa-8225-0b1c00be7782.png">

but when I click on button nothing happening no error no event triggering

**Comment by tmcconechy** [comment]
@suryapasem what team is this for. We don't recommend this pattern because you can never use the keyboard on it correctly and the events get all mixed up (when you click a cell which one should it click). Instead put only one button per cell.

Please review your design and look at doing one per cell https://main-enterprise.demo.design.infor.com/components/datagrid/test-icon-buttons.html (you can make the columns smaller than this example so its only the size of a button)

**Comment by tmcconechy** [comment]
Or use an actions button https://main-enterprise.demo.design.infor.com/components/datagrid/test--actions-reload-list.html with multiple actions

**Comment by suryapasem** [comment]
@tmcconechy  

This is Solution & Innovations team.

I will discuss your suggestions with my manager.

Thanks for your suggestions on this.

**Comment by tmcconechy** [comment]
For now we wont add 3 buttons in a cell. Because the accessibility wont work. Try

- actions button https://main-enterprise.demo.design.infor.com/components/datagrid/test--actions-reload-list.html
- use seperate cells for each button
