### ISSUE TITLE
IdsDataGrid: When pressing Shift+(ArrowUp/ArrowDown) on the row instead of row being selected nothing happens.

### ISSUE THREAD

**Issue by jjorge1999** [infor-design/enterprise-wc#1330]
**Describe the bug**
When pressing Shift+(ArrowUp/ArrowDown) instead of row being selected nothing happens.

**To Reproduce**

1. Go to 'http://localhost:4300/ids-data-grid/multiple-selection.html'
2. Select atleast 1 row.
3. Press Shift+(ArrowUp/ArrowDown) 

**Expected behavior**
Multi-select the rows with cell navigation when Shift is pressed. 

**Version**

- ids-enterprise-wc: 1.0.0-beta.11

**Screenshots**
<img width="952" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/122866382/4c3a4a62-0b4a-41c0-b2ef-496937328005">

https://github.com/infor-design/enterprise-wc/assets/122866382/2220b107-f7d1-4d8c-9fe4-e68c1b5a6108

**Platform**
-Infor Application/Team Name: M3 UX
-OS Version: Windows 11
-Browser Name: chrome
-Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
@jjorge1999 Im not sure that shift and arrow key is correct behavior can you try https://github.com/infor-design/enterprise-wc/pull/1370

Since space or enter selects that should be involved somehow.

- shift + enter should select row ranged between the two clicks
- but shift + arrow should only check if space or enter is used?

**Comment by glenlieorillo** [comment]
Working as expected using the shift key+arrow up/down to select row/s.


https://github.com/infor-design/enterprise-wc/assets/102151352/94191a27-e948-4331-b18b-66b9d7aececb
