### ISSUE TITLE
IdsSplitter: Add new web component 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#143]
**Describe the bug**

Bring over the current splitter component.  See if we can simplify and improve the code at all while improving as we go. Current splitter component https://master-enterprise.demo.design.infor.com/components/splitter

```
Markup to be added
```

**Functionality to bring over**
- Supports both x and y splitter
- Supports nesting in both cases important https://github.com/infor-design/enterprise/issues/2697
- May need a parent container in the pattern
- Keep current designs
- Resizes inner containers to 100% those items are slots

**Additional context**
- 100% test coverage
- DOCS, CHANGE log ect. 
- https://github.com/infor-design/enterprise-wc/blob/master/doc/CHECKLIST.MD
- themes 

See completed components like card, tag, badge, hyperlink as reference

**Comment by rob2d** [comment]
Just to update on the scope of this component after discussing with @tmcconechy and @deep7102 today: a lot of the core functionality seems should be abstractable/delegated to a specific component (`<ids-draggable>`), which would also be needed for some base functionalities in other components such as `ids-toast`. 

`ids-splitter` would then just be a wrapper/container pattern with width-setting/height-setting around that, which lowers the complexity of it quite a bit after that.

Created a ticket for this (#253 ) and working on it now as pre-req for the sake of scope creep/review-ability and getting it in the codebase for usage.

**Comment by rob2d** [comment]
After some iteration now that the first stage on draggable is done, I think this approach on the interface may work:

### Basic example
```html
<ids-splitter axis="x">
  <ids-splitter-pane min-size="30%" max-size="50%">
    some content in a child div
  </ids-splitter-pane>
  <ids-splitter-pane>
    some content in a child div
  </ids-splitter-pane>
</ids-splitter>
```

### Nested content

```html
<ids-splitter axis="x">
  <ids-splitter-pane min-size="30%" max-size="50%" size="25%">
    H1
  </ids-splitter-pane>
  <ids-splitter-pane>
    <ids-splitter axis="y">
      <ids-splitter-pane min-size="20%" size="20%">
        H2/V1 (20% of height for content)
      </ids-splitter-pane>
      <ids-splitter-pane>
        H2/V2
      </ids-splitter-pane>
    </ids-splitter>
  </ids-splitter-pane>
</ids-splitter>
```

It seems would be nice to also not need to contain the splitter pane in the case where we have a nested splitter (since it doesn't make too much sense to have just a floating splitter in a pane, and the splitter fills-to-size as default style in any case).

```html
<ids-splitter axis="x">
  <ids-splitter-pane min-size="30%" max-size="50%" size="25%">
    H1
  </ids-splitter-pane>
  <ids-splitter axis="y">
    <ids-splitter-pane min-size="20%" size="20%">
      H2/V1 (20% of height for content)
    </ids-splitter-pane>
    <ids-splitter-pane>
      H2/V2
    </ids-splitter-pane>
  </ids-splitter>
</ids-splitter>
```
---------------------------------------
(draggables/etc populate in shadowDom)

Mainly the idea was if we need multi splitters the axis can be DRY and things can be managed in the parent-only. For the size I left a unit on it to try to make it flexible, and maybe we can try to auto-fit content but haven't implemented this yet. Just illustrating in case anyone has thoughts/input on this before a PR comes up.

**Comment by rob2d** [comment]
After a convo with @deep7102  on `containment` property and also mulling on it I think there can be some other changes/additions now to `ids-draggable` here (or possibly may open a new PR depending on how much scope increases but shouldn't be too much). 

(1) for containment, that should be an optional enum vs `parent-containment` flag and renamed e.g. 

```html
<ids-draggable bounds="parent" ></ids-draggable>
```

^ similar to current `<ids-draggable parent-containment >...` but so that we can use selectors or set it to `viewport` as well.

(2) a new property for `relative-bounds` to support `max-size` e.g.

```html
<ids-draggable 
  bounded-by="parent"
  relative-bounds="left: 10; right: 20; bottom: 40; top: 50"
>...</ids-draggable>
```

Some trade-offs are made here with having a string there but it would be easier to implement/test since we ave some logic that can bound the element by a specific rectangle with adjustment for `parent-containment`, so just adding to the bounds in each direction shouldn't be bad (and also directly linkable to the `max-size` prop this way through each side).

Also used that syntax after thinking on it because it would be easy to parse and resembles the `style` attrib (just need to add a hash in the setter to make sure that writing equivalent things in different orders doesn't re-set /WIP).

**Comment by EdwardCoyle** [comment]
@rob2d this sounds like something that could be generalized to apply the idea of "containment" more broadly.  In the Popup, I had roughed out a [system for parent containment against a `containingElem` property](https://github.com/infor-design/enterprise-wc/blob/main/src/ids-popup/ids-popup.js#L541-L559) that's just a reference to the "boundary" element, which defaults to `document.body`.  It might be better served by something like what you and @deep7102 discussed.

**Comment by rob2d** [comment]
@EdwardCoyle good point/great idea thanks 👍

Could be worth just to make sure that the pattern/attrib is generalizable when reviewing on this branch. 

------------------------------

Some notes on that for anyone who's thinking about this or who is aware of components that can use the functionality:

(1) with `ids-draggable` on `ids-dragstart`, the containing `rect` on the drag has to be returned exactly 1x and probably would not need to rely on a ResizeObserver yet for safety since it doesn't make sense that things should be changing often with the containers during drag in 99% of cases we currently have (so would need a flag to track with resize observer then not have callbacks fired or destroy the instance to not bloat up app if it was in a frequent component).

(2) I actually purposely didn't include a DOM selector on that previous comment quite yet since it requires some more thought.

One thing @deep7102 and I were discussing was the `containment` property could be an element and maybe we could have some syntax (was going to bring it up tomorrow) like `(selector)`, to not need to have a 2nd attribute besides `containment` like `container` (with a selector) and also not explicitly overloading the behavior of the property without some obvious syntax diff (which should ideally be minimal/easily parsible; since technically things without `.` or `#` can be WCs). 

(3) there was an exception case with the `viewport` (vs document) as well which the `ids-splitter` and `ids-toast` need to consider, and currently the  `parent` is actually not a string selector since it has to be scanned based on size and we can't guarantee a unique one exists.

(4) Just one note on the current `containingElem`: if we have it as an attribute vs a property for an interface, it may make more sense to have it as a selector (string) since its serializable with an optional setter... since we can't use an HTMLElement as a ref. 

It may also be worth to consider how we can handle ref/attribute selectors; there was something briefly mentioned on Tuesday which is LitElement has a syntax to get references in it's template and that may be useful to consider how to implement for this sort of thing as well (but this point isn't entirely necessary here, just that if we ever had a solution it would be super useful on this sort of "selector" attribute).

-----------------
For that sort of functionality (or util) to be adequately generalized, it seems like maybe it could stand to be it's own ticket -- does not stop us from trying to do that with it in mind of course.

(And again, great input and sounds like a holistic/qualitative idea, so am mostly just providing context with this and without any intention to deliberately push off or detract from it)
