### ISSUE TITLE
IdsTree: Add an addNodes() function

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1517]
**Describe the bug**
Would like a programmatic way of adding nodes to a tree.

For our drill around feature content outside the tree can add nodes to the tree.

**Expected behavior**
Calling `IdsTree.addNodes([nodes], parentNodeSelector: string, expand?: boolean)` would add child nodes to the parentNode.

**Version**
- ids-enterprise-wc: latest

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: latest

**Comment by tmcconechy** [comment]
Should add the nodes to the UI and the dataset attached

**Comment by jbrcna** [comment]
this issue is now fixed. 
https://main.wc.design.infor.com/ids-tree/add-node.html
<img width="523" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/554bdeac-f3ec-4630-9957-2bac0adf5f39">

**Observation**
when you add multiple nodes (As children of selected folder). 
`Uncaught RangeError: Maximum call stack size exceeded`
may i clarify if this is an expected result?
<img width="1713" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a99ccee8-49c1-45e2-9a25-49ab1ecdab22">

**Comment by tmcconechy** [comment]
@jbrcna no, that wouldnt be expected/good. Can you raise an issue with the steps and i'll look?

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy . a new ticket has been created.
