### ISSUE TITLE
Auto-scroll does not work on Widgets

### ISSUE THREAD

**Issue by NelsonCBG** [infor-design/enterprise-wc#1795]
Hi infor-design team, one of our colleagues has been working on dashboard type widget, which shows production orders split by company and work centers. Since it shows lots of information, we would like the widget to automatically scroll through the different work centers, like for instance, the flights information panes we can see in airports. Also in this case, our team tried, but the scrolling seems to have issues working on the Soho interface. Attached you can see a test webpage that auto-scroll, and the documentation on what was done. The same code placed in the widget, does not work. Thanks for your advice.

BR,
Nelson
[AutoScroll_Documentation.pdf](https://github.com/infor-design/enterprise-wc/files/14038586/AutoScroll_Documentation.pdf)
[test_page.zip](https://github.com/infor-design/enterprise-wc/files/14038608/test_page.zip)

**Comment by tmcconechy** [comment]
I think in general this is not a great idea because of a) accessibility issues b) usability issues c) user frustration if they dont want this behavior. But can review it with the design team.

The widgets themselves just have a scroll container which would be the same as the page. So if you really need to do this i dont see why this would be an issue. We do have some code using the events however to show an effect on the widget.

Maybe try it here https://github.com/infor-design/enterprise/blob/main/app/views/components/cards/example-workspace-widgets.html

Maybe as an idea you could disable scrolling on the default widget (noscroll class). Then make a new container with the scroll events or trun off the current scroll events (problem is you wont get the nice scroll effect).

This may be out of scope for components but will review if we want to provide an example.

**Comment by tmcconechy** [comment]
@NelsonCBG also is this for web components or https://github.com/infor-design/enterprise ?

**Comment by NelsonCBG** [comment]
Hi Tim, I get your point, indeed our idea is having an enable/disable button to control the auto-scroll. So we could leave it on when presented in big screens showed bythe plants, but any user interacting with it could stop it. We're using these widgets in Infor OS, so I believe it's enterprise. I'm talking to my colleague Santosh to see if he can work out on your suggestions. We will keep you posted.

**Comment by tmcconechy** [comment]
Ok cool Yes i think that the issue might be that line where we are doing our on scroll effect in the code. See if he can work with that 👍🏻
