### ISSUE TITLE
Hyperlink: Option to appear link without underline

### ISSUE THREAD

**Issue by jomcab** [infor-design/enterprise-wc#2029]
**Is your feature request related to a problem or use case? Please describe.**
Use case: to present links in a bit more modern look.

**Describe the solution you'd like**
An option to display links that is blue and bold.

**Describe alternatives you've considered**
We currently use what's available which is blue text with underline to follow IDS standard.

**Additional context**
See "Forgot email?" and other links below:
<img width="240" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/12105280/67aa5232-5ed9-4e1c-bdff-f4e4b62d644c">

**Comment by tmcconechy** [comment]
@jomcab we have this option..

```js
elem.textDecoration = "none"
```

or

```html
<ids-hyperlink text-decoration="none">My Link</ids-hyperlink>
```

NOTE: For some use cases this is ok but we dont necessarily recommend changing all links like this. We have the line because of accessibility. 

https://eastsideco.com/blog/underline-or-not-underline-question#:~:text=In%20accordance%20with%20the%20web,and%20considered%20piece%20of%20design.
