### ISSUE TITLE
Charts: Not resizing in mobile and window size change

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2181]
**Describe the bug**
Charts are not resizing when changing viewport and in mobile.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-area-chart/example.html
2. Resize browser
3. Chart doesn't resize
4. Repeat with steps with the link below:
    - https://main.wc.design.infor.com/ids-axis-chart/example.html
    - https://main.wc.design.infor.com/ids-bar-chart/example.html
    - https://main.wc.design.infor.com/ids-line-chart/example.html
    - https://main.wc.design.infor.com/ids-pie-chart/example.html

**Expected behavior**
Charts resizes based on browser's dimensions

**Version**
- ids-enterprise: v1.0.0-beta.23

**Screenshots**
**Axis Chart**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/71330335-ff72-4450-a6e9-a20287b57ead)

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/f69c7df0-5efc-400e-96cc-ecf827c260d0)

**Area Chart**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/19e36d7c-ced3-49c8-8c8e-c9ec2a6d9535)

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/4b8d9689-4e43-4068-bef8-f925dc979fbb)

**Bar Chart**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/5ee092d6-26d0-4ae7-8b2d-0ab76c3ef8b1)

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/ce077df5-5ed4-47ce-abf2-e621c00a31d8)

**Line Chart**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/d61d0686-4bed-4c71-af1c-01b091d0c563)

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/848cc07a-8ead-4e9e-90fc-399ca2e6bef4)

**Pie Chart**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/d55b599d-d9aa-4eca-99d9-342a633139c9)

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/2c2553ab-a80d-4355-9434-067b35daa596)

**Comment by tmcconechy** [comment]
@n-ace-ancog i thought this was a bug but its not. All the default examples show a fixed size chart. But there is responsive examples in each section for each chart. So to see that behavior use those.

It requires some setup of parent size so its not the default. And i think thats ok since its 

https://main.wc.design.infor.com/ids-axis-chart/responsive.html
https://main.wc.design.infor.com/ids-line-chart/responsive.html
https://main.wc.design.infor.com/ids-pie-chart/example.html -> sort of responsive but bad example layout
