### ISSUE TITLE
IdsSlider: min value with type "step" doesn't work

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2484]
**Describe the bug**
Setting a min value on a slider with type `step` doesn't work. It always defaults to `0`.

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-enterprise-wc-120-utztve?file=index.html
2. Notice that the first 3 sliders (which don't set a min value) work
3. Notice that the 4th slider (which sets a min value) doesn't work, it just always defaults to `0`

**Expected behavior**
It should be possible to set a min value on a slider with type `step`

**Version**
- ids-enterprise-wc: `1.2.0`

**Platform**
 - Infor Application/Team Name: `OS Portal`

**Comment by tmcconechy** [comment]
@radovaniljic Working on this i think there is a problem using `min` with `stepCount` since it would be hard to do the math between a min and max value i.e. it goes 10 - 100 but the number of steps shown is 10 the math would be all decimals.

Did you really want a step-interval here? I.E.

10 - 20 - 30 - 40 - 50 -60 - 70 -80 -90 -100

```
<ids-slider type="step" step-interval="10" min="10" max="100" show-tooltip></ids-slider>
```

I'm proposing a new setting `step-interval` that can be used for this case?

**Comment by radovaniljic** [comment]
@tmcconechy yes a `step-interval` setting would be great.
