### ISSUE TITLE
IdsHeaderTabs:  Add new web component (or tab setting)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#279]
**Is your feature request related to a problem or use case? Please describe.**

Add a ids header examples. Try and use the placement in the header and inverse. Or add a setting. Finally new component if necessary.

Also any tabs cleanup and todos you want to resolve https://github.com/infor-design/enterprise-wc/blob/main/src/ids-tabs/TODO.md with aim to get header tabs working

**Phase 1 Features (MVP)**

- Simple default example https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
- Example with additional text area ? Extended Header? https://main-enterprise.demo.design.infor.com/components/personalize/example-form.html

**Possible Internal Markup**
```js
  <ids-header>
    ..
    <ids-tabs>...</ids-tabs>
  </ids-header>
```

**Suggested Dependencies**
- ids-inverse-color-mixin (indirectly?)
- ids-tabs
- ids-header

**Other**
Pass the following checklist ordered in priority (some may be left for later) https://github.com/infor-design/enterprise-wc/blob/main/doc/CHECKLIST.md

**Comment by rob2d** [comment]
Based on #146 and getting up to speed with these tabs again, to support some other use cases it seems at least basic overflow can be considered in this iteration on IdsTabs. 


Since it looks like users already have a use case with customization (including sizing), it seems like we could also remove ShadowDOM container (e.g. just use a slot as template) and directly nest the tabs within it (mainly `:host` + `.ids-component` breaks sizing even if using `part` so that they have to redundantly specify height/width...). Hopefully makes accessibility easier as well.

Also on the bright side, #291 seems to have fixed link-hashing/sharing on Wizard which was going to be used on IdsTabs so maybe could fit that in here depending on how the sprint is going.
