### ISSUE TITLE
Chore: Improve Bundling to reduce consistency

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#290]
**Describe the bug**
Something (may) be wrong with our bundling but not sure. 

**To Reproduce**
1. Go to ids-theme-mixin and add
```
import { attributes } from '../ids-base/ids-attributes';

console.log('In IdsThemeMixin');

/**
 * A mixin that adds theming functionality to components
 * @param {any} superclass Accepts a superclass and creates a new subclass from it
 * @returns {any} The extended object
 */
const IdsThemeMixin = (superclass) => class extends superclass {
  constructor() {
    super();
  }
```
2. Go to http://localhost:4300/ids-button
3. Check console

**Requirements**
- We do have the requirement that each component can be imported by itself with what it needs to run standalone/side by side
- We also need each mixin to have its own shared instance i.e. the events mixin has a map and event 
- should not give CSP errors (some bundlers did use an eval which was flagged)

**Expected behavior**
We do have the requirement that each component can be imported by itself. But is there someway to reduce the redundancy?

**Additional context**
We could use import instead and import from the npm folder like the locale scripts do https://webpack.js.org/api/module-methods/#import-1

Or better perhaps changing to ESM will work https://github.com/infor-design/enterprise-wc/blob/main/webpack.config.js#L55-L57

**Comment by tmcconechy** [comment]
Could one solution be to "switch" to ESM https://webpack.js.org/guides/ecma-script-modules/#flagging-modules-as-esm

**Comment by rob2d** [comment]
Found the reason why this behavior wasn't familiar: Webpack changed their default behavior of the "runtime" so in v5 (and v4 updates), the default behavior of chunks from sharing a `single` instance to having one on each module as-it's-loading. From their doc on the runtime @ https://webpack.js.org/concepts/manifest/#runtime

> It contains the loading and resolving logic needed to connect your modules as they interact. This includes connecting modules that have already been loaded into the browser as well as logic to lazy-load the ones that haven't.

In our case we have technically only one core "app" but have separate entrypoints just due to the structure of our demo dist to not include everything, which is not a usual use-case since most  libs are either SPAs or use babel and are tree-shaken. Was reading a bit also and looking at other repos and it seems the common approach is to provide the npm dist as a module system that a user can pull from. 

But anyway at least changing the runtime option to single seems to solve the issues with `instanceof` checks on #143 I was having also 🙂
