### ISSUE TITLE
Bug: Several bugs found doing react examples

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#384]
**Describe the bug**
Issues appearing in in enterprise-wc

- [x] ids-data-grid console error when selecting grid cells `Cannot read properties of null (reading 'parentNode')`
- [ ] ids-color-picker when no label attr is present is misaligned
- [ ] ids-checkbox when no label attr is present is misaligned
- [x] ids-tree is cut off fixed here https://github.com/infor-design/enterprise-wc/pull/381/files#diff-3e863fa632d1cf70443162b57f5de54f3951f6d1ae063a37db7bc2e181e0a539R1

**Additional context**
https://github.com/infor-design/enterprise-wc-examples/pull/5

**Comment by tmcconechy** [comment]
@andriivarhanov do you think these are still issues im not sure about the 2 remaining ones exactly?

**Comment by andriivarhanov** [comment]
@tmcconechy I've checked recent version and the issues are still there.
Steps to reproduce for `ids-color-picker`:
- Go to `demos/ids-color-picker/example.html` and remove `label` attributes
- Go to http://localhost:4300/ids-color-picker and see input values are misaligned
![image](https://user-images.githubusercontent.com/5204821/141442103-0fb1b5c8-4904-48ab-a217-4315bb3aa148.png)
- See the input has `color-input-value-no-label` css class with `padding-top` css property

Seems like a quick fix to remove the padding. It's not an issue if `ids-color-picker` is going to be used with a label, i.e. label is required. 

Steps to reproduce for `ids-checkbox`:
- Go to `demos/ids-checkbox/example.html` and remove some labels
- Go to http://localhost:4300/ids-checkbox and see no label checkboxes are misaligned 
![image](https://user-images.githubusercontent.com/5204821/141444607-5fd80246-e4ec-4bf3-bba3-cccd028a6a9b.png)

Can be fixed with css only and it's not an issue if the label is required for the component

**Comment by tmcconechy** [comment]
Thanks.  Yes i think this is a valid case. What we should do is.

a) add a LABEL_AUDIBLE option that adds the audible mixin/class so they can have a valid label thats invisible
b) if LABEL and LABEL_AUDIBLE are both empty put &nbsp in for the label (or make it work without with css)

**Comment by andriivarhanov** [comment]
@tmcconechy makes sense, should I do it?

**Comment by tmcconechy** [comment]
@andriivarhanov i was going to save this issue for a developer (Jeff) to help ramp him up

**Comment by tmcconechy** [comment]
assigned to Jeff but waiting on his email to come through so assigning to me
