### ISSUE TITLE
Device Specs Util: Update from deprecated API

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#398]
**Describe the bug**
The [device specs util](https://github.com/infor-design/enterprise-wc/blob/main/src/utils/ids-device-env-specs-utils/ids-device-env-specs-utils.js#L18) is currently referencing a browser API, [`navigator.platform`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform) and [`navigator.appName`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appCodeName) that is considered deprecated.

**To Reproduce**
n/a

**Expected behavior**
It's recommended by MDN that we switch to a newer browser API, [`navigator.userAgentData.platform`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/platform)

**Version**
current `main`

**Additional context**
Used in the IdsAbout component

**Comment by tmcconechy** [comment]
See also https://github.com/infor-design/enterprise/issues/5803 if you spot a fix on the way for it it could be something to fix/add in both versions

**Comment by clecidor** [comment]
It turns out that navigator.userAgentData is only available in Secure Contexts (HTTPS), and returns undefined in unsecured sites (HTTP).  It also doesn’t seem to be supported by recent versions of Safari (confirmed on my local machine).  See https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgent

Because of the Secret Context constraint, JSDom does not provide the navigator.userAgentData value, so it needs to be mocked…  Since this returns undefined in insecure contexts, there are adverse implications for users of this web-component library on sites that do not have HTTPS enabled.  We could have code that falls back to navigator.platform, but then we’d be back to square-one, right?

NOTE: There is a way to fetch UserAgent data asynchronously using `navigator.userAgentData.getHighEntropyValues` but this doesn’t appear to be available in Safari (tested locally).  See https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData#returning_high_entropy_values

Furthermore, I have yet to find clear and stable alternatives for other deprecated properties like navigator.appName and navigator.appVersion… For instance, we have logic around navigator.appName to determine the appropriate language value in Microsoft Internet Explorer… see https://github.com/infor-design/enterprise-wc/blob/main/src/utils/ids-device-env-specs-utils/ids-device-env-specs-utils.js#L19

So this apparently isn’t a quick fix, and, I’ve decided to hold off on my changes until I can obtain some clarity on solid approaches to addressing the above concerns… thoughts?

**Comment by tmcconechy** [comment]
@clecidor @EdwardCoyle i think given it only works on https and not in all our supported browsers. We might have to wait until this API is more broadly supported. I don't think the deprecated API is going to be removed that soon.

Think we could still fix https://github.com/infor-design/enterprise/issues/5803 however. (but not urgent)

**Comment by tmcconechy** [comment]
Will hold on this for now until the API imporves so taking it out.
