### ISSUE TITLE
IdsAppMenu: Remove IDS Logo from App menu

### ISSUE THREAD

**Issue by danielortiz1982** [infor-design/enterprise-wc#851]
Remove IDS Logo from WC App menu

**Screenshots**

<img width="830" alt="Screen Shot 2022-08-10 at 1 43 54 PM" src="https://user-images.githubusercontent.com/5215954/183981012-d0f4ab58-58bf-45b1-8579-fe39ebbbed07.png">

**Additional context**

**Comment by tmcconechy** [comment]
Put this in planning for discussion next grooming session. This can be done but need to know:

- why remove them and the reasoning behind it so that if anyone asks
- and that we can document this in the change log
- should any logos appearing any-were be removed? 
- should the entire logo itself be removed from the icons? ect

**Comment by tmcconechy** [comment]
Related issues:
https://github.com/infor-design/enterprise/issues/6468
https://github.com/infor-design/enterprise/issues/6642
