### ISSUE TITLE
IdsDataGrid: Add option to override hyperlink href attribute

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise-wc#861]
**Is your feature request related to a problem or use case? Please describe.**
When using the datagrid in certain frameworks the user may want to override the default use of `href`. For example, Angular makes use of a custom attribute `routerLink` to initiate navigation.

**Describe the solution you'd like**
Add an option to `ids-hyperlink` or the `ids-data-grid` hyperlink formatter to override the use of `href`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tmcconechy** [comment]
@jmacaluso711 looking into this a bit .. when NG provides a `routerLink` it will alter the href attribute so the link works. So i think this should actually "almost" work. Except we might need to remove the default of href of `#` and add it to the datagrid columns?

Does that seem right? So NG will use routerLink on the root hyperlink and that will change the href which will change in the link in the shadowRoot?

Otherwise if we watch `routerLink` directly we have issues since only lower case is supported.

**Comment by tmcconechy** [comment]
from @jmacaluso711 :  After reviewing this it seems this may not be the best approach. Since routerLink is a directive, if it's added in our library it won't be processed by Angular and will just be a string. Best approach might be to add a listener for click on the Angular side and use the router to navigate. Just need to make sure to document it

**Comment by tmcconechy** [comment]
Maybe close this once the docs are in place?
