### ISSUE TITLE
General: Improve sourcemaps for Angular debugging

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise-wc#905]
**Describe the bug**
Currently sourcemaps are not working properly in Angular.

Research any adjustments that could be made on our end to improve sourcemaps for Angular. Possible it's in the angular.json configuration however could be something in our dev build causing the issue?

**To Reproduce**

1. Pull angular-ids-wc example branch https://github.com/infor-design/enterprise-wc-examples/tree/316-angular-examples
2. `npm i && start`
3. go to any component, open dev tools and go to source tab
4. See there are no source files available for debugging.

**Expected behavior**
Expect to see source files for all ids-enterprise-wc components

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
n/a

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
n/a

**Comment by tmcconechy** [comment]
@jmacaluso711 i did think about this basically you could build and / or publish the npm package both with and without the source map:

https://github.com/infor-design/enterprise-wc/blob/main/package.json#L41-L42

But its a security issue (also flagged by SSO) for shipping it with prod code https://github.com/infor-design/enterprise/issues/6489 so not shipped with maps.

So what you can do is do `npm run build:dist` and link it if you want to debug. We could also think about publishing a second npm package for debugging or a cdn link or something? But thinking because of this we cant publish with debug info.
