### ISSUE TITLE
IdsDataGrid: Filter Improvements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#932]
**Describe the bug**
List of additional things to do with the filter row.

- [ ] https://github.com/infor-design/enterprise-wc/issues/667
- [x] Add full test coverage to `ids-data-grid.ts.html` or remove unneeded code
- [x] Improve Types
- [x] disableClientFilter setting (ignores filtering / ui only with a way to get the filter info by an event)
- [x] Confirm all the following work or have equivalents:  FilterTypes.Date, FilterTypes.Integer, FilterTypes.Decimal, FilterTypes.Dropdown, FilterTypes.Text, FilterTypes.Custom
- [x] On http://localhost:4300/ids-data-grid/filter.html the "In Stock" (boolean?) filter is not working

**Comment by jbrcna** [comment]
https://main.wc.design.infor.com/ids-data-grid/filter-trigger-fields.html
`safari`
dropdown of last 3 columns were affected.
<img width="711" alt="image" src="https://user-images.githubusercontent.com/56722184/198448948-af910992-4643-4b62-9d46-b1a0f3af5db3.png">

https://main.wc.design.infor.com/ids-data-grid/filter-trigger-fields.html
when the table is empty user is unable to change the dates because the calendar is inside the table
<img width="833" alt="image" src="https://user-images.githubusercontent.com/56722184/198457802-8b21e971-0cfd-4404-a0f7-7b48670bdd23.png">

**Comment by tmcconechy** [comment]
@jbrcna this is already reported / known issue https://github.com/infor-design/enterprise-wc/issues/667 we are working on that....

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy
